export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_REGISTER: '/verify-register',
  FORGET_PASSWORD: '/forget-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  DOCTORS: '/doctors',
  DISEASES: '/diseases',
  MEDICINES: '/medicines',
  NEWS: '/news',
  BOOKING: '/appointment',
  POLICY: '/policy',
  PROCEDURES: '/procedures',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_MEDICINES: '/admin/medicines',
  ADMIN_DISEASES: '/admin/diseases',
  ADMIN_NEWS: '/admin/news',
  ADMIN_AGGREGATE: '/admin/aggregate',
  MEDICAL_RECORD: '/profile/patient/medical_record',
  MEDICAL_RECORD_UPCOMING: '/profile/patient/medical_record/upcoming'
};
